version: '3'

services:
  bot:
    container_name: 'vote-bot'
    env_file:
      - .env
    build:
      context: '.'
    depends_on:
      - redis
      - postgres
    networks:
      - bot-network
  redis:
    image: 'redis:latest'
    container_name: 'redis-container'
    volumes:
      - ./save-data/redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - bot-network
  postgres:
    image: 'postgres:14.4'
    container_name: 'postgres-container'
    environment:
      POSTGRES_DB: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U=${POSTGRES_USER} -d=${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5050:5432'
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./save-data/postgres:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge